name: Dave Roxas' Portfolio!
title: Dave Roxas' Portfolio | These are the games I've worked on with great people!
description: These are the games I've been a part with!
tags:
  - dev
  - gamedev
  - jekyll
  - theme
  - netlify
email: roxasdavelouie@yahoo.com
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about

# Social Media Settings
# Remove the item if you don't need it
github_username: daveroxas14
# facebook_username: facebook_username
twitter_username: davidzchu
# instagram_username: instagram_username
linkedin_username: dave-louie-roxas
# medium_username: medium_username

# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed
  
# Advanced Settings
url: ""
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
use_logo: false
theme: jekflix
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-paginate-content
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
use_logo: false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
