
# title: Dave Louie Roxas' Portfolio!
# email: roxasdavelouie@yahoo.com
#description: >- # this means to ignore newlines until "baseurl:"
#  These are the games I've been a part with!
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: davidzchu
# github_username:  daveroxas14

name: Dave Louie Roxas' Portfolio!
title: Dave Louie Roxas' Portfolio
description: These are the games I've been a part with!
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: roxasdavelouie@yahoo.com
# disqus_username: disqus_username
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml

# Social Media Settings
# Remove the item if you don't need it
github_username: daveroxas14
# facebook_username: facebook_username
twitter_username: davidzchu
# instagram_username: instagram_username
linkedin_username: dave-louie-roxas
# medium_username: medium_username

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed


# Build settings
theme: jekflix
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
